In [13]:
import sys
import datetime
import pandas as pd

sys.path.append('../')
from src.util.functions import Functions

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = '../data'
path_csv = '{path_data}/csv'.format(path_data=path_data)
csv_out_name = '{path_csv}/covid19-{level}.csv'.format(path_csv=path_csv, level=level)

In [14]:
url_cum = Functions.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [15]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2020-11-20T17:00:00,ITA,33957,3748,37705,739471,777176,15505,37242,520022,48569,825417.0,520350.0,1345767,19962604,11999674.0,NaN
271,2020-11-21T17:00:00,ITA,34063,3758,37821,753925,791746,14570,34767,539524,49261,844177.0,536354.0,1380531,20199829,12120989.0,NaN
272,2020-11-22T17:00:00,ITA,34279,3801,38080,767867,805947,14201,28337,553098,49823,858957.0,549911.0,1408868,20388576,12225850.0,NaN
273,2020-11-23T17:00:00,ITA,34697,3810,38507,758342,796849,-9098,22930,584493,50453,870461.0,561334.0,1431795,20537521,12303705.0,NaN
274,2020-11-24T17:00:00,ITA,34577,3816,38393,759993,798386,1537,23232,605330,51306,882238.0,572784.0,1455022,20726180,12398952.0,NaN

In [16]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2020-11-20T17:00:00,33957,3748,37705,739471,777176,15505,37242,520022,48569,825417.0,520350.0,1345767,19962604,11999674.0
271,2020-11-21T17:00:00,34063,3758,37821,753925,791746,14570,34767,539524,49261,844177.0,536354.0,1380531,20199829,12120989.0
272,2020-11-22T17:00:00,34279,3801,38080,767867,805947,14201,28337,553098,49823,858957.0,549911.0,1408868,20388576,12225850.0
273,2020-11-23T17:00:00,34697,3810,38507,758342,796849,-9098,22930,584493,50453,870461.0,561334.0,1431795,20537521,12303705.0
274,2020-11-24T17:00:00,34577,3816,38393,759993,798386,1537,23232,605330,51306,882238.0,572784.0,1455022,20726180,12398952.0

In [17]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi,casi_testati,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,8623,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,9587,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,12014,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,15695,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2020-11-20T17:00:00,33957,3748,37705,739471,777176,15505,37242,520022,48569,...,19962604,11999674.0,36.0,347.0,383.0,15122.0,21035.0,699.0,238077.0,116853.0
271,2020-11-21T17:00:00,34063,3758,37821,753925,791746,14570,34767,539524,49261,...,20199829,12120989.0,10.0,106.0,116.0,14454.0,19502.0,692.0,237225.0,121315.0
272,2020-11-22T17:00:00,34279,3801,38080,767867,805947,14201,28337,553098,49823,...,20388576,12225850.0,43.0,216.0,259.0,13942.0,13574.0,562.0,188747.0,104861.0
273,2020-11-23T17:00:00,34697,3810,38507,758342,796849,-9098,22930,584493,50453,...,20537521,12303705.0,9.0,418.0,427.0,-9525.0,31395.0,630.0,148945.0,77855.0
274,2020-11-24T17:00:00,34577,3816,38393,759993,798386,1537,23232,605330,51306,...,20726180,12398952.0,6.0,-120.0,-114.0,1651.0,20837.0,853.0,188659.0,95247.0

In [18]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi,casi_testati,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,8623,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,9587,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,12014,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,15695,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,18661,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2020-11-20T17:00:00,33957,3748,37705,739471,777176,15505,37242,520022,48569,...,19962604,11999674.0,36.0,347.0,383.0,15122.0,21035.0,699.0,238077.0,116853.0
271,2020-11-21T17:00:00,34063,3758,37821,753925,791746,14570,34767,539524,49261,...,20199829,12120989.0,10.0,106.0,116.0,14454.0,19502.0,692.0,237225.0,121315.0
272,2020-11-22T17:00:00,34279,3801,38080,767867,805947,14201,28337,553098,49823,...,20388576,12225850.0,43.0,216.0,259.0,13942.0,13574.0,562.0,188747.0,104861.0
273,2020-11-23T17:00:00,34697,3810,38507,758342,796849,-9098,22930,584493,50453,...,20537521,12303705.0,9.0,418.0,427.0,-9525.0,31395.0,630.0,148945.0,77855.0
274,2020-11-24T17:00:00,34577,3816,38393,759993,798386,1537,23232,605330,51306,...,20726180,12398952.0,6.0,-120.0,-114.0,1651.0,20837.0,853.0,188659.0,95247.0

In [19]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['nuovi_positivi'] / (df_n['totale_positivi'] - df_n['nuovi_positivi'] + df_n['nuovi_dimessi_guariti'] + df_n['nuovi_deceduti'])) * 100).round(3)
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,0.0,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,42.081
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,25.080
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,42.0,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,64.935
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,1.0,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,40.476
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,4.0,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,29.233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2020-11-20T17:00:00,33957,3748,37705,739471,777176,15505,37242,520022,48569,...,21035.0,699.0,238077.0,116853.0,9.94,4.85,15.64,31.87,0.97,4.890
271,2020-11-21T17:00:00,34063,3758,37821,753925,791746,14570,34767,539524,49261,...,19502.0,692.0,237225.0,121315.0,9.94,4.78,14.66,28.66,0.27,4.474
272,2020-11-22T17:00:00,34279,3801,38080,767867,805947,14201,28337,553098,49823,...,13574.0,562.0,188747.0,104861.0,9.98,4.72,15.01,27.02,1.14,3.579
273,2020-11-23T17:00:00,34697,3810,38507,758342,796849,-9098,22930,584493,50453,...,31395.0,630.0,148945.0,77855.0,9.89,4.83,15.39,29.45,0.24,2.845
274,2020-11-24T17:00:00,34577,3816,38393,759993,798386,1537,23232,605330,51306,...,20837.0,853.0,188659.0,95247.0,9.94,4.81,12.31,24.39,0.16,2.916

In [20]:
df_n.to_csv(csv_out_name, index=False)

In [25]:
df_n[['totale_positivi', 'var_pos_perc', 'variazione_totale_positivi']]
# df_n.columns

     totale_positivi  var_pos_perc  variazione_totale_positivi
1                311        42.081                          90
2                385        25.080                          74
3                588        64.935                         203
4                821        40.476                         233
5               1049        29.233                         228
..               ...           ...                         ...
270           777176         4.890                       15505
271           791746         4.474                       14570
272           805947         3.579                       14201
273           796849         2.845                       -9098
274           798386         2.916                        1537

[274 rows x 3 columns]