In [1]:
import sys
import datetime
import pandas as pd

sys.path.append('../')
from src.util.functions import Functions

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = '../data'
path_csv = '{path_data}/csv'.format(path_data=path_data)
csv_out_name = '{path_csv}/covid19-{level}.csv'.format(path_csv=path_csv, level=level)

In [2]:
url_cum = Functions.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [3]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note,ingressi_terapia_intensiva,note_test,note_casi
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,2020-12-27T17:00:00,ITA,23571,2580,26151,555609,581760,817,8913,1394011,71925,NaN,NaN,2047696,26046137,14656053.0,NaN,148.0,NaN,NaN
308,2020-12-28T17:00:00,ITA,23932,2565,26497,548724,575221,-6539,8585,1408686,72370,NaN,NaN,2056277,26114818,14685718.0,NaN,167.0,NaN,NaN
309,2020-12-29T17:00:00,ITA,23662,2549,26211,542517,568728,-6493,11224,1425730,73029,NaN,NaN,2067487,26243558,14731420.0,NaN,256.0,NaN,NaN
310,2020-12-30T17:00:00,ITA,23566,2528,26094,538301,564395,-4333,16202,1445690,73604,NaN,NaN,2083689,26412603,14795168.0,NaN,175.0,NaN,NaN
311,2020-12-31T17:00:00,ITA,23151,2555,25706,544190,569896,5501,23477,1463111,74159,NaN,NaN,2107166,26598607,14871966.0,NaN,202.0,NaN,NaN

In [4]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,ingressi_terapia_intensiva,note_test,note_casi
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,2020-12-27T17:00:00,23571,2580,26151,555609,581760,817,8913,1394011,71925,NaN,NaN,2047696,26046137,14656053.0,148.0,NaN,NaN
308,2020-12-28T17:00:00,23932,2565,26497,548724,575221,-6539,8585,1408686,72370,NaN,NaN,2056277,26114818,14685718.0,167.0,NaN,NaN
309,2020-12-29T17:00:00,23662,2549,26211,542517,568728,-6493,11224,1425730,73029,NaN,NaN,2067487,26243558,14731420.0,256.0,NaN,NaN
310,2020-12-30T17:00:00,23566,2528,26094,538301,564395,-4333,16202,1445690,73604,NaN,NaN,2083689,26412603,14795168.0,175.0,NaN,NaN
311,2020-12-31T17:00:00,23151,2555,25706,544190,569896,5501,23477,1463111,74159,NaN,NaN,2107166,26598607,14871966.0,202.0,NaN,NaN

In [5]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,note_test,note_casi,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,2020-12-27T17:00:00,23571,2580,26151,555609,581760,817,8913,1394011,71925,...,NaN,NaN,0.0,259.0,259.0,558.0,7798.0,298.0,59879.0,24757.0
308,2020-12-28T17:00:00,23932,2565,26497,548724,575221,-6539,8585,1408686,72370,...,NaN,NaN,-15.0,361.0,346.0,-6885.0,14675.0,445.0,68681.0,29665.0
309,2020-12-29T17:00:00,23662,2549,26211,542517,568728,-6493,11224,1425730,73029,...,NaN,NaN,-16.0,-270.0,-286.0,-6207.0,17044.0,659.0,128740.0,45702.0
310,2020-12-30T17:00:00,23566,2528,26094,538301,564395,-4333,16202,1445690,73604,...,NaN,NaN,-21.0,-96.0,-117.0,-4216.0,19960.0,575.0,169045.0,63748.0
311,2020-12-31T17:00:00,23151,2555,25706,544190,569896,5501,23477,1463111,74159,...,NaN,NaN,27.0,-415.0,-388.0,5889.0,17421.0,555.0,186004.0,76798.0

In [6]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,note_test,note_casi,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,NaN,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,2020-12-27T17:00:00,23571,2580,26151,555609,581760,817,8913,1394011,71925,...,NaN,NaN,0.0,259.0,259.0,558.0,7798.0,298.0,59879.0,24757.0
308,2020-12-28T17:00:00,23932,2565,26497,548724,575221,-6539,8585,1408686,72370,...,NaN,NaN,-15.0,361.0,346.0,-6885.0,14675.0,445.0,68681.0,29665.0
309,2020-12-29T17:00:00,23662,2549,26211,542517,568728,-6493,11224,1425730,73029,...,NaN,NaN,-16.0,-270.0,-286.0,-6207.0,17044.0,659.0,128740.0,45702.0
310,2020-12-30T17:00:00,23566,2528,26094,538301,564395,-4333,16202,1445690,73604,...,NaN,NaN,-21.0,-96.0,-117.0,-4216.0,19960.0,575.0,169045.0,63748.0
311,2020-12-31T17:00:00,23151,2555,25706,544190,569896,5501,23477,1463111,74159,...,NaN,NaN,27.0,-415.0,-388.0,5889.0,17421.0,555.0,186004.0,76798.0

In [7]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['variazione_totale_positivi'] / (df_n['totale_positivi'] - df_n['variazione_totale_positivi'])) * 100).round(2)
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,0.0,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,40.72
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,23.79
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,42.0,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,52.73
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,1.0,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,39.63
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,4.0,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,27.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,2020-12-27T17:00:00,23571,2580,26151,555609,581760,817,8913,1394011,71925,...,7798.0,298.0,59879.0,24757.0,9.87,4.50,14.89,36.00,0.00,0.14
308,2020-12-28T17:00:00,23932,2565,26497,548724,575221,-6539,8585,1408686,72370,...,14675.0,445.0,68681.0,29665.0,9.68,4.61,12.50,28.94,-0.58,-1.12
309,2020-12-29T17:00:00,23662,2549,26211,542517,568728,-6493,11224,1425730,73029,...,17044.0,659.0,128740.0,45702.0,9.72,4.61,8.72,24.56,-0.62,-1.13
310,2020-12-30T17:00:00,23566,2528,26094,538301,564395,-4333,16202,1445690,73604,...,19960.0,575.0,169045.0,63748.0,9.69,4.62,9.58,25.42,-0.82,-0.76
311,2020-12-31T17:00:00,23151,2555,25706,544190,569896,5501,23477,1463111,74159,...,17421.0,555.0,186004.0,76798.0,9.94,4.51,12.62,30.57,1.07,0.97

In [8]:
df_n.to_csv(csv_out_name, index=False)

In [9]:
df_n[['totale_positivi', 'var_pos_perc', 'variazione_totale_positivi']]
# df_n.columns

     totale_positivi  var_pos_perc  variazione_totale_positivi
1                311         40.72                          90
2                385         23.79                          74
3                588         52.73                         203
4                821         39.63                         233
5               1049         27.77                         228
..               ...           ...                         ...
307           581760          0.14                         817
308           575221         -1.12                       -6539
309           568728         -1.13                       -6493
310           564395         -0.76                       -4333
311           569896          0.97                        5501

[311 rows x 3 columns]