In [1]:
import sys
import datetime
import pandas as pd

sys.path.append('../')
from src.util.functions import Functions

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = '../data'
path_csv = '{path_data}/csv'.format(path_data=path_data)
csv_out_name = '{path_csv}/covid19-{level}.csv'.format(path_csv=path_csv, level=level)

In [2]:
url_cum = Functions.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [3]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2020-11-11T17:00:00,ITA,29444,3081,32525,580833,613358,23248,32961,372113,42953,657205.0,371219.0,1028424,17965836,10891971.0,NaN
262,2020-11-12T17:00:00,ITA,29873,3170,33043,602011,635054,21696,37978,387758,43589,674591.0,391810.0,1066401,18200508,11025449.0,NaN
263,2020-11-13T17:00:00,ITA,30914,3230,34144,629782,663926,28872,40902,399238,44139,697312.0,409991.0,1107303,18455416,11170324.0,NaN
264,2020-11-14T17:00:00,ITA,31398,3306,34704,653731,688435,24509,37255,411434,44683,718482.0,426070.0,1144552,18683111,11305441.0,NaN
265,2020-11-15T17:00:00,ITA,32047,3422,35469,677021,712490,24055,33979,420810,45229,736846.0,441683.0,1178529,18878386,11416172.0,NaN

In [4]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2020-11-11T17:00:00,29444,3081,32525,580833,613358,23248,32961,372113,42953,657205.0,371219.0,1028424,17965836,10891971.0
262,2020-11-12T17:00:00,29873,3170,33043,602011,635054,21696,37978,387758,43589,674591.0,391810.0,1066401,18200508,11025449.0
263,2020-11-13T17:00:00,30914,3230,34144,629782,663926,28872,40902,399238,44139,697312.0,409991.0,1107303,18455416,11170324.0
264,2020-11-14T17:00:00,31398,3306,34704,653731,688435,24509,37255,411434,44683,718482.0,426070.0,1144552,18683111,11305441.0
265,2020-11-15T17:00:00,32047,3422,35469,677021,712490,24055,33979,420810,45229,736846.0,441683.0,1178529,18878386,11416172.0

In [5]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi,casi_testati,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,8623,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,9587,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,12014,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,15695,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2020-11-11T17:00:00,29444,3081,32525,580833,613358,23248,32961,372113,42953,...,17965836,10891971.0,110.0,811.0,921.0,22327.0,9090.0,623.0,225640.0,126410.0
262,2020-11-12T17:00:00,29873,3170,33043,602011,635054,21696,37978,387758,43589,...,18200508,11025449.0,89.0,429.0,518.0,21178.0,15645.0,636.0,234672.0,133478.0
263,2020-11-13T17:00:00,30914,3230,34144,629782,663926,28872,40902,399238,44139,...,18455416,11170324.0,60.0,1041.0,1101.0,27771.0,11480.0,550.0,254908.0,144875.0
264,2020-11-14T17:00:00,31398,3306,34704,653731,688435,24509,37255,411434,44683,...,18683111,11305441.0,76.0,484.0,560.0,23949.0,12196.0,544.0,227695.0,135117.0
265,2020-11-15T17:00:00,32047,3422,35469,677021,712490,24055,33979,420810,45229,...,18878386,11416172.0,116.0,649.0,765.0,23290.0,9376.0,546.0,195275.0,110731.0

In [6]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi,casi_testati,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,8623,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,9587,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,12014,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,15695,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,18661,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2020-11-11T17:00:00,29444,3081,32525,580833,613358,23248,32961,372113,42953,...,17965836,10891971.0,110.0,811.0,921.0,22327.0,9090.0,623.0,225640.0,126410.0
262,2020-11-12T17:00:00,29873,3170,33043,602011,635054,21696,37978,387758,43589,...,18200508,11025449.0,89.0,429.0,518.0,21178.0,15645.0,636.0,234672.0,133478.0
263,2020-11-13T17:00:00,30914,3230,34144,629782,663926,28872,40902,399238,44139,...,18455416,11170324.0,60.0,1041.0,1101.0,27771.0,11480.0,550.0,254908.0,144875.0
264,2020-11-14T17:00:00,31398,3306,34704,653731,688435,24509,37255,411434,44683,...,18683111,11305441.0,76.0,484.0,560.0,23949.0,12196.0,544.0,227695.0,135117.0
265,2020-11-15T17:00:00,32047,3422,35469,677021,712490,24055,33979,420810,45229,...,18878386,11416172.0,116.0,649.0,765.0,23290.0,9376.0,546.0,195275.0,110731.0

In [7]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['nuovi_positivi'] / (df_n['totale_positivi'] - df_n['nuovi_positivi'] + df_n['nuovi_dimessi_guariti'] + df_n['nuovi_deceduti'])) * 100).round(3)
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,0.0,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,42.081
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,25.080
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,42.0,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,64.935
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,1.0,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,40.476
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,4.0,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,29.233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,2020-11-11T17:00:00,29444,3081,32525,580833,613358,23248,32961,372113,42953,...,9090.0,623.0,225640.0,126410.0,9.47,5.30,14.61,26.07,3.70,5.586
262,2020-11-12T17:00:00,29873,3170,33043,602011,635054,21696,37978,387758,43589,...,15645.0,636.0,234672.0,133478.0,9.59,5.20,16.18,28.45,2.89,6.192
263,2020-11-13T17:00:00,30914,3230,34144,629782,663926,28872,40902,399238,44139,...,11480.0,550.0,254908.0,144875.0,9.46,5.14,16.05,28.23,1.89,6.441
264,2020-11-14T17:00:00,31398,3306,34704,653731,688435,24509,37255,411434,44683,...,12196.0,544.0,227695.0,135117.0,9.53,5.04,16.36,27.57,2.35,5.611
265,2020-11-15T17:00:00,32047,3422,35469,677021,712490,24055,33979,420810,45229,...,9376.0,546.0,195275.0,110731.0,9.65,4.98,17.40,30.69,3.51,4.936

In [8]:
df_n.to_csv(csv_out_name, index=False)