In [1]:
import sys
import datetime
import pandas as pd

sys.path.append('../')
from src.util.functions import Functions

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = '../data'
path_csv = '{path_data}/csv'.format(path_data=path_data)
csv_out_name = '{path_csv}/covid19-{level}.csv'.format(path_csv=path_csv, level=level)

In [2]:
url_cum = Functions.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [3]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,...,tamponi,casi_testati,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,...,8623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,...,9587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,...,12014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,...,15695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2021-01-30T17:00:00,ITA,20098,2218,22316,441036,463352,-4472,12715,1990152,...,32453362,16923532.0,NaN,132.0,NaN,NaN,2526058.0,15725.0,30718540.0,1734822.0
342,2021-01-31T17:00:00,ITA,20096,2215,22311,431657,453968,-9384,11252,2010548,...,32666726,17005122.0,NaN,97.0,NaN,NaN,2536779.0,16253.0,30840359.0,1826367.0
343,2021-02-01T17:00:00,ITA,20260,2252,22512,425077,447589,-6379,7925,2024523,...,32809145,17053960.0,NaN,145.0,NaN,NaN,2544428.0,16529.0,30916110.0,1893035.0
344,2021-02-02T17:00:00,ITA,20317,2214,22531,415234,437765,-9824,9660,2043500,...,33053574,17129160.0,NaN,158.0,NaN,NaN,2552713.0,17895.0,31041506.0,2012068.0
345,2021-02-03T17:00:00,ITA,20071,2145,22216,412506,434722,-3043,13189,2059248,...,33332881,17222062.0,NaN,133.0,NaN,NaN,2564627.0,19163.0,31199437.0,2133444.0

In [4]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note', 'note_test', 'note_casi'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,ingressi_terapia_intensiva,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2021-01-30T17:00:00,20098,2218,22316,441036,463352,-4472,12715,1990152,88279,NaN,NaN,2541783,32453362,16923532.0,132.0,2526058.0,15725.0,30718540.0,1734822.0
342,2021-01-31T17:00:00,20096,2215,22311,431657,453968,-9384,11252,2010548,88516,NaN,NaN,2553032,32666726,17005122.0,97.0,2536779.0,16253.0,30840359.0,1826367.0
343,2021-02-01T17:00:00,20260,2252,22512,425077,447589,-6379,7925,2024523,88845,NaN,NaN,2560957,32809145,17053960.0,145.0,2544428.0,16529.0,30916110.0,1893035.0
344,2021-02-02T17:00:00,20317,2214,22531,415234,437765,-9824,9660,2043500,89343,NaN,NaN,2570608,33053574,17129160.0,158.0,2552713.0,17895.0,31041506.0,2012068.0
345,2021-02-03T17:00:00,20071,2145,22216,412506,434722,-3043,13189,2059248,89820,NaN,NaN,2583790,33332881,17222062.0,133.0,2564627.0,19163.0,31199437.0,2133444.0

In [5]:
df_nd.columns

Index(['data', 'ricoverati_con_sintomi', 'terapia_intensiva',
       'totale_ospedalizzati', 'isolamento_domiciliare', 'totale_positivi',
       'variazione_totale_positivi', 'nuovi_positivi', 'dimessi_guariti',
       'deceduti', 'casi_da_sospetto_diagnostico', 'casi_da_screening',
       'totale_casi', 'tamponi', 'casi_testati', 'ingressi_terapia_intensiva',
       'totale_positivi_test_molecolare',
       'totale_positivi_test_antigenico_rapido', 'tamponi_test_molecolare',
       'tamponi_test_antigenico_rapido'],
      dtype='object')

In [6]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2021-01-30T17:00:00,20098,2218,22316,441036,463352,-4472,12715,1990152,88279,...,30718540.0,1734822.0,-52.0,-299.0,-351.0,-4121.0,16764.0,421.0,298010.0,89375.0
342,2021-01-31T17:00:00,20096,2215,22311,431657,453968,-9384,11252,2010548,88516,...,30840359.0,1826367.0,-3.0,-2.0,-5.0,-9379.0,20396.0,237.0,213364.0,81590.0
343,2021-02-01T17:00:00,20260,2252,22512,425077,447589,-6379,7925,2024523,88845,...,30916110.0,1893035.0,37.0,164.0,201.0,-6580.0,13975.0,329.0,142419.0,48838.0
344,2021-02-02T17:00:00,20317,2214,22531,415234,437765,-9824,9660,2043500,89343,...,31041506.0,2012068.0,-38.0,57.0,19.0,-9843.0,18977.0,498.0,244429.0,75200.0
345,2021-02-03T17:00:00,20071,2145,22216,412506,434722,-3043,13189,2059248,89820,...,31199437.0,2133444.0,-69.0,-246.0,-315.0,-2728.0,15748.0,477.0,279307.0,92902.0

In [7]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,NaN,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2021-01-30T17:00:00,20098,2218,22316,441036,463352,-4472,12715,1990152,88279,...,30718540.0,1734822.0,-52.0,-299.0,-351.0,-4121.0,16764.0,421.0,298010.0,89375.0
342,2021-01-31T17:00:00,20096,2215,22311,431657,453968,-9384,11252,2010548,88516,...,30840359.0,1826367.0,-3.0,-2.0,-5.0,-9379.0,20396.0,237.0,213364.0,81590.0
343,2021-02-01T17:00:00,20260,2252,22512,425077,447589,-6379,7925,2024523,88845,...,30916110.0,1893035.0,37.0,164.0,201.0,-6580.0,13975.0,329.0,142419.0,48838.0
344,2021-02-02T17:00:00,20317,2214,22531,415234,437765,-9824,9660,2043500,89343,...,31041506.0,2012068.0,-38.0,57.0,19.0,-9843.0,18977.0,498.0,244429.0,75200.0
345,2021-02-03T17:00:00,20071,2145,22216,412506,434722,-3043,13189,2059248,89820,...,31199437.0,2133444.0,-69.0,-246.0,-315.0,-2728.0,15748.0,477.0,279307.0,92902.0

In [8]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['variazione_totale_positivi'] / (df_n['totale_positivi'] - df_n['variazione_totale_positivi'])) * 100).round(2)
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,0.0,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,40.72
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,23.79
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,42.0,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,52.73
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,1.0,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,39.63
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,4.0,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,27.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2021-01-30T17:00:00,20098,2218,22316,441036,463352,-4472,12715,1990152,88279,...,16764.0,421.0,298010.0,89375.0,9.94,4.82,4.27,14.23,-2.29,-0.96
342,2021-01-31T17:00:00,20096,2215,22311,431657,453968,-9384,11252,2010548,88516,...,20396.0,237.0,213364.0,81590.0,9.93,4.91,5.27,13.79,-0.14,-2.03
343,2021-02-01T17:00:00,20260,2252,22512,425077,447589,-6379,7925,2024523,88845,...,13975.0,329.0,142419.0,48838.0,10.00,5.03,5.56,16.23,1.67,-1.41
344,2021-02-02T17:00:00,20317,2214,22531,415234,437765,-9824,9660,2043500,89343,...,18977.0,498.0,244429.0,75200.0,9.83,5.15,3.95,12.85,-1.69,-2.19
345,2021-02-03T17:00:00,20071,2145,22216,412506,434722,-3043,13189,2059248,89820,...,15748.0,477.0,279307.0,92902.0,9.66,5.11,4.72,14.20,-3.12,-0.70

In [9]:
df_n.to_csv(csv_out_name, index=False)

In [10]:
df_n[['totale_positivi', 'var_pos_perc', 'variazione_totale_positivi']]
# df_n.columns

     totale_positivi  var_pos_perc  variazione_totale_positivi
1                311         40.72                          90
2                385         23.79                          74
3                588         52.73                         203
4                821         39.63                         233
5               1049         27.77                         228
..               ...           ...                         ...
341           463352         -0.96                       -4472
342           453968         -2.03                       -9384
343           447589         -1.41                       -6379
344           437765         -2.19                       -9824
345           434722         -0.70                       -3043

[345 rows x 3 columns]