In [1]:
import sys
import time
import requests
import datetime
import pandas as pd

sys.path.append('../')
from src.util.functions import Functions

# Disable warning
pd.options.mode.chained_assignment = None

level = 'province'

path_data = '../data'
path_csv = '{path_data}/csv'.format(path_data=path_data)
csv_out_name = '{path_csv}/covid19-{level}.csv'.format(path_csv=path_csv, level=level)

In [2]:
url_cum = Functions.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'

In [3]:
df_raw_p = pd.read_csv(url_cum)
df_raw_p.columns

Index(['data', 'stato', 'codice_regione', 'denominazione_regione',
       'codice_provincia', 'denominazione_provincia', 'sigla_provincia', 'lat',
       'long', 'totale_casi', 'note', 'codice_nuts_1', 'codice_nuts_2',
       'codice_nuts_3'],
      dtype='object')

In [4]:
cols_to_drop = ['stato', 'lat', 'long', 'note']
df_pd = df_raw_p.drop(cols_to_drop, axis=1)
df_pd

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2020-02-24T18:00:00,13,Abruzzo,66,L'Aquila,AQ,0,NaN,NaN,NaN
1,2020-02-24T18:00:00,13,Abruzzo,67,Teramo,TE,0,NaN,NaN,NaN
2,2020-02-24T18:00:00,13,Abruzzo,68,Pescara,PE,0,NaN,NaN,NaN
3,2020-02-24T18:00:00,13,Abruzzo,69,Chieti,CH,0,NaN,NaN,NaN
4,2020-02-24T18:00:00,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
48987,2021-02-03T17:00:00,5,Veneto,27,Venezia,VE,50372,ITH,ITH3,ITH35
48988,2021-02-03T17:00:00,5,Veneto,28,Padova,PD,57724,ITH,ITH3,ITH36
48989,2021-02-03T17:00:00,5,Veneto,29,Rovigo,RO,9697,ITH,ITH3,ITH37
48990,2021-02-03T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,4253,ITH,ITH3,NaN
48991,2021-02-03T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,569,ITH,ITH3,NaN

In [5]:
last_date_str = df_pd.iloc[-1].data.split('T')[0]
last_date = datetime.datetime.strptime(last_date_str, '%Y-%m-%d')
prev_date = Functions.get_previous_date(last_date)
prev_date_str = datetime.datetime.strftime(prev_date, '%Y-%m-%d')
last_date_str, prev_date_str

('2021-02-03', '2021-02-02')

In [6]:
df_raw_p_1 = df_pd[df_pd.data.str.startswith(last_date_str)]
df_raw_p_1

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
48843,2021-02-03T17:00:00,13,Abruzzo,66,L'Aquila,AQ,12239,ITF,ITF1,ITF11
48844,2021-02-03T17:00:00,13,Abruzzo,67,Teramo,TE,11207,ITF,ITF1,ITF12
48845,2021-02-03T17:00:00,13,Abruzzo,68,Pescara,PE,9620,ITF,ITF1,ITF13
48846,2021-02-03T17:00:00,13,Abruzzo,69,Chieti,CH,10020,ITF,ITF1,ITF14
48847,2021-02-03T17:00:00,13,Abruzzo,879,Fuori Regione / Provincia Autonoma,NaN,366,ITF,ITF1,NaN
...,...,...,...,...,...,...,...,...,...,...
48987,2021-02-03T17:00:00,5,Veneto,27,Venezia,VE,50372,ITH,ITH3,ITH35
48988,2021-02-03T17:00:00,5,Veneto,28,Padova,PD,57724,ITH,ITH3,ITH36
48989,2021-02-03T17:00:00,5,Veneto,29,Rovigo,RO,9697,ITH,ITH3,ITH37
48990,2021-02-03T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,4253,ITH,ITH3,NaN
48991,2021-02-03T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,569,ITH,ITH3,NaN

In [7]:
df_raw_p_0 = df_pd[df_pd.data.str.startswith(prev_date_str)]
df_raw_p_0

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
48694,2021-02-02T17:00:00,13,Abruzzo,66,L'Aquila,AQ,12189,ITF,ITF1,ITF11
48695,2021-02-02T17:00:00,13,Abruzzo,67,Teramo,TE,11129,ITF,ITF1,ITF12
48696,2021-02-02T17:00:00,13,Abruzzo,68,Pescara,PE,9447,ITF,ITF1,ITF13
48697,2021-02-02T17:00:00,13,Abruzzo,69,Chieti,CH,9896,ITF,ITF1,ITF14
48698,2021-02-02T17:00:00,13,Abruzzo,879,Fuori Regione / Provincia Autonoma,NaN,363,ITF,ITF1,NaN
...,...,...,...,...,...,...,...,...,...,...
48838,2021-02-02T17:00:00,5,Veneto,27,Venezia,VE,50277,ITH,ITH3,ITH35
48839,2021-02-02T17:00:00,5,Veneto,28,Padova,PD,57590,ITH,ITH3,ITH36
48840,2021-02-02T17:00:00,5,Veneto,29,Rovigo,RO,9668,ITH,ITH3,ITH37
48841,2021-02-02T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,4235,ITH,ITH3,NaN
48842,2021-02-02T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,575,ITH,ITH3,NaN

In [8]:
# State S
df_raw_p_1 = df_raw_p_1.sort_values(by='codice_provincia').reset_index(drop=True)
df_raw_p_1

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2021-02-03T17:00:00,1,Piemonte,1,Torino,TO,117970,ITC,ITC1,ITC11
1,2021-02-03T17:00:00,1,Piemonte,2,Vercelli,VC,8374,ITC,ITC1,ITC12
2,2021-02-03T17:00:00,1,Piemonte,3,Novara,NO,17717,ITC,ITC1,ITC15
3,2021-02-03T17:00:00,1,Piemonte,4,Cuneo,CN,30901,ITC,ITC1,ITC16
4,2021-02-03T17:00:00,1,Piemonte,5,Asti,AT,11634,ITC,ITC1,ITC17
...,...,...,...,...,...,...,...,...,...,...
144,2021-02-03T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN
145,2021-02-03T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN
146,2021-02-03T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN
147,2021-02-03T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,9,ITC,ITC2,NaN
148,2021-02-03T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,569,ITH,ITH3,NaN

In [9]:
# State S - 1
df_raw_p_0 = df_raw_p_0.sort_values(by='codice_provincia').reset_index(drop=True)
df_raw_p_0

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2021-02-02T17:00:00,1,Piemonte,1,Torino,TO,117479,ITC,ITC1,ITC11
1,2021-02-02T17:00:00,1,Piemonte,2,Vercelli,VC,8343,ITC,ITC1,ITC12
2,2021-02-02T17:00:00,1,Piemonte,3,Novara,NO,17656,ITC,ITC1,ITC15
3,2021-02-02T17:00:00,1,Piemonte,4,Cuneo,CN,30823,ITC,ITC1,ITC16
4,2021-02-02T17:00:00,1,Piemonte,5,Asti,AT,11611,ITC,ITC1,ITC17
...,...,...,...,...,...,...,...,...,...,...
144,2021-02-02T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN
145,2021-02-02T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN
146,2021-02-02T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN
147,2021-02-02T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,9,ITC,ITC2,NaN
148,2021-02-02T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,575,ITH,ITH3,NaN

In [10]:
df_p = df_raw_p_1.copy()
df_p['variazione_totale_casi'] = df_raw_p_1['totale_casi'] - df_raw_p_0['totale_casi']
df_p

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3,variazione_totale_casi
0,2021-02-03T17:00:00,1,Piemonte,1,Torino,TO,117970,ITC,ITC1,ITC11,491
1,2021-02-03T17:00:00,1,Piemonte,2,Vercelli,VC,8374,ITC,ITC1,ITC12,31
2,2021-02-03T17:00:00,1,Piemonte,3,Novara,NO,17717,ITC,ITC1,ITC15,61
3,2021-02-03T17:00:00,1,Piemonte,4,Cuneo,CN,30901,ITC,ITC1,ITC16,78
4,2021-02-03T17:00:00,1,Piemonte,5,Asti,AT,11634,ITC,ITC1,ITC17,23
...,...,...,...,...,...,...,...,...,...,...,...
144,2021-02-03T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN,0
145,2021-02-03T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN,0
146,2021-02-03T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN,0
147,2021-02-03T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,9,ITC,ITC2,NaN,0
148,2021-02-03T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,569,ITH,ITH3,NaN,-6

In [11]:
# Write df to csv
df_p.to_csv(csv_out_name, index=False)