In [1]:
import sys
import datetime
import numpy as np
import pandas as pd

path_root = '../..'
sys.path.append(f'{path_root}/')
from src.util.functions import Functions as F

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = f'{path_root}/data'
path_csv = f'{path_data}/csv'
csv_out_name = f'{path_csv}/covid19-{level}.csv'

In [2]:
url_cum = F.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [3]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,...,tamponi,casi_testati,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,...,8623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,...,9587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,...,12014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,...,15695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2022-01-10T17:00:00,ITA,16340,1606,17946,1986651,2004597,60618,101762,5410482,...,148771952,42856913.0,NaN,114.0,NaN,NaN,6286591.0,1267753.0,76085265.0,72686687.0
687,2022-01-11T17:00:00,ITA,17067,1677,18744,2115395,2134139,129542,220532,5500938,...,150147466,43105796.0,NaN,185.0,NaN,NaN,6361711.0,1413152.0,76403257.0,73744209.0
688,2022-01-12T17:00:00,ITA,17309,1669,18978,2203082,2222060,87921,196224,5609136,...,151338033,43353643.0,NaN,156.0,NaN,NaN,6434616.0,1536452.0,76764844.0,74573189.0
689,2022-01-13T17:00:00,ITA,17648,1668,19316,2304202,2323518,101458,184615,5691939,...,152519212,43584304.0,NaN,156.0,NaN,NaN,6506687.0,1648958.0,77098992.0,75420220.0
690,2022-01-14T17:00:00,ITA,18019,1679,19698,2379130,2398828,75310,186253,5817138,...,153651521,43803735.0,NaN,136.0,NaN,NaN,6580117.0,1776397.0,77413988.0,76237533.0

In [4]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note', 'note_test', 'note_casi'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,ingressi_terapia_intensiva,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2022-01-10T17:00:00,16340,1606,17946,1986651,2004597,60618,101762,5410482,139265,NaN,NaN,7554344,148771952,42856913.0,114.0,6286591.0,1267753.0,76085265.0,72686687.0
687,2022-01-11T17:00:00,17067,1677,18744,2115395,2134139,129542,220532,5500938,139559,NaN,NaN,7774863,150147466,43105796.0,185.0,6361711.0,1413152.0,76403257.0,73744209.0
688,2022-01-12T17:00:00,17309,1669,18978,2203082,2222060,87921,196224,5609136,139872,NaN,NaN,7971068,151338033,43353643.0,156.0,6434616.0,1536452.0,76764844.0,74573189.0
689,2022-01-13T17:00:00,17648,1668,19316,2304202,2323518,101458,184615,5691939,140188,NaN,NaN,8155645,152519212,43584304.0,156.0,6506687.0,1648958.0,77098992.0,75420220.0
690,2022-01-14T17:00:00,18019,1679,19698,2379130,2398828,75310,186253,5817138,140548,NaN,NaN,8356514,153651521,43803735.0,136.0,6580117.0,1776397.0,77413988.0,76237533.0

In [5]:
list(df_nd.columns)

['data',
 'ricoverati_con_sintomi',
 'terapia_intensiva',
 'totale_ospedalizzati',
 'isolamento_domiciliare',
 'totale_positivi',
 'variazione_totale_positivi',
 'nuovi_positivi',
 'dimessi_guariti',
 'deceduti',
 'casi_da_sospetto_diagnostico',
 'casi_da_screening',
 'totale_casi',
 'tamponi',
 'casi_testati',
 'ingressi_terapia_intensiva',
 'totale_positivi_test_molecolare',
 'totale_positivi_test_antigenico_rapido',
 'tamponi_test_molecolare',
 'tamponi_test_antigenico_rapido']

In [6]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2022-01-10T17:00:00,16340,1606,17946,1986651,2004597,60618,101762,5410482,139265,...,76085265.0,72686687.0,11.0,693.0,704.0,59914.0,56560.0,227.0,612821.0,131900.0
687,2022-01-11T17:00:00,17067,1677,18744,2115395,2134139,129542,220532,5500938,139559,...,76403257.0,73744209.0,71.0,727.0,798.0,128744.0,90456.0,294.0,1375514.0,248883.0
688,2022-01-12T17:00:00,17309,1669,18978,2203082,2222060,87921,196224,5609136,139872,...,76764844.0,74573189.0,-8.0,242.0,234.0,87687.0,108198.0,313.0,1190567.0,247847.0
689,2022-01-13T17:00:00,17648,1668,19316,2304202,2323518,101458,184615,5691939,140188,...,77098992.0,75420220.0,-1.0,339.0,338.0,101120.0,82803.0,316.0,1181179.0,230661.0
690,2022-01-14T17:00:00,18019,1679,19698,2379130,2398828,75310,186253,5817138,140548,...,77413988.0,76237533.0,11.0,371.0,382.0,74928.0,125199.0,360.0,1132309.0,219431.0

In [7]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,NaN,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2022-01-10T17:00:00,16340,1606,17946,1986651,2004597,60618,101762,5410482,139265,...,76085265.0,72686687.0,11.0,693.0,704.0,59914.0,56560.0,227.0,612821.0,131900.0
687,2022-01-11T17:00:00,17067,1677,18744,2115395,2134139,129542,220532,5500938,139559,...,76403257.0,73744209.0,71.0,727.0,798.0,128744.0,90456.0,294.0,1375514.0,248883.0
688,2022-01-12T17:00:00,17309,1669,18978,2203082,2222060,87921,196224,5609136,139872,...,76764844.0,74573189.0,-8.0,242.0,234.0,87687.0,108198.0,313.0,1190567.0,247847.0
689,2022-01-13T17:00:00,17648,1668,19316,2304202,2323518,101458,184615,5691939,140188,...,77098992.0,75420220.0,-1.0,339.0,338.0,101120.0,82803.0,316.0,1181179.0,230661.0
690,2022-01-14T17:00:00,18019,1679,19698,2379130,2398828,75310,186253,5817138,140548,...,77413988.0,76237533.0,11.0,371.0,382.0,74928.0,125199.0,360.0,1132309.0,219431.0

In [8]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['variazione_totale_positivi'] / (df_n['totale_positivi'] - df_n['variazione_totale_positivi'])) * 100).round(2)
df_n['np_log'] = np.log10(df_n['nuovi_positivi'])
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc,np_log
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,40.72,1.968483
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,23.79,1.892095
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,52.73,2.397940
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,39.63,2.376577
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,27.77,2.380211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2022-01-10T17:00:00,16340,1606,17946,1986651,2004597,60618,101762,5410482,139265,...,227.0,612821.0,131900.0,8.95,0.90,16.61,77.15,0.69,3.12,5.007586
687,2022-01-11T17:00:00,17067,1677,18744,2115395,2134139,129542,220532,5500938,139559,...,294.0,1375514.0,248883.0,8.95,0.88,16.03,88.61,4.42,6.46,5.343472
688,2022-01-12T17:00:00,17309,1669,18978,2203082,2222060,87921,196224,5609136,139872,...,313.0,1190567.0,247847.0,8.79,0.85,16.48,79.17,-0.48,4.12,5.292752
689,2022-01-13T17:00:00,17648,1668,19316,2304202,2323518,101458,184615,5691939,140188,...,316.0,1181179.0,230661.0,8.64,0.83,15.63,80.04,-0.06,4.57,5.266267
690,2022-01-14T17:00:00,18019,1679,19698,2379130,2398828,75310,186253,5817138,140548,...,360.0,1132309.0,219431.0,8.52,0.82,16.45,84.88,0.66,3.24,5.270103

In [9]:
df_n.to_csv(csv_out_name, index=False)

In [10]:
df_n[['totale_positivi', 'var_pos_perc', 'variazione_totale_positivi']]
# df_n.columns

     totale_positivi  var_pos_perc  variazione_totale_positivi
1                311         40.72                          90
2                385         23.79                          74
3                588         52.73                         203
4                821         39.63                         233
5               1049         27.77                         228
..               ...           ...                         ...
686          2004597          3.12                       60618
687          2134139          6.46                      129542
688          2222060          4.12                       87921
689          2323518          4.57                      101458
690          2398828          3.24                       75310

[690 rows x 3 columns]