In [1]:
import sys
import datetime
import pandas as pd

path_root = '../..'
sys.path.append(f'{path_root}/')
from src.util.functions import Functions as F

# Disable warning
pd.options.mode.chained_assignment = None 

level = 'andamento-nazionale'

path_data = f'{path_root}/data'
path_csv = f'{path_data}/csv'
csv_out_name = f'{path_csv}/covid19-{level}.csv'

In [2]:
url_cum = F.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'

In [3]:
df_n_raw = pd.read_csv(url_cum)
df_n_raw

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,...,tamponi,casi_testati,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,...,4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,...,8623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,...,9587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,...,12014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,...,15695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2021-04-11T17:00:00,ITA,27251,3585,30836,502169,533005,-80,15746,3122555,...,53054866,23920532.0,NaN,175.0,NaN,NaN,3645548.0,124266.0,42107589.0,10947277.0
413,2021-04-12T17:00:00,ITA,27329,3593,30922,493495,524417,-8588,9789,3140565,...,53245501,23970623.0,NaN,167.0,NaN,NaN,3655050.0,124544.0,42200462.0,11045039.0
414,2021-04-13T17:00:00,ITA,26952,3526,30478,488742,519220,-5197,13447,3158725,...,53550491,24058301.0,NaN,242.0,NaN,NaN,3667114.0,125919.0,42353108.0,11197383.0
415,2021-04-14T17:00:00,ITA,26369,3490,29859,484801,514660,-4560,16168,3178976,...,53885257,24160306.0,NaN,216.0,NaN,NaN,3682451.0,126742.0,42550896.0,11334361.0
416,2021-04-15T17:00:00,ITA,25587,3417,29004,481019,510023,-4637,16974,3200196,...,54204890,24260858.0,NaN,211.0,NaN,NaN,3698718.0,127438.0,42736949.0,11467941.0

In [4]:
# Drop unused columns
df_nd = df_n_raw.drop(['stato', 'note', 'note_test', 'note_casi'], axis=1)
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,ingressi_terapia_intensiva,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,NaN,NaN,229,4324,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,NaN,NaN,322,8623,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,NaN,NaN,400,9587,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,NaN,NaN,650,12014,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,NaN,NaN,888,15695,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2021-04-11T17:00:00,27251,3585,30836,502169,533005,-80,15746,3122555,114254,NaN,NaN,3769814,53054866,23920532.0,175.0,3645548.0,124266.0,42107589.0,10947277.0
413,2021-04-12T17:00:00,27329,3593,30922,493495,524417,-8588,9789,3140565,114612,NaN,NaN,3779594,53245501,23970623.0,167.0,3655050.0,124544.0,42200462.0,11045039.0
414,2021-04-13T17:00:00,26952,3526,30478,488742,519220,-5197,13447,3158725,115088,NaN,NaN,3793033,53550491,24058301.0,242.0,3667114.0,125919.0,42353108.0,11197383.0
415,2021-04-14T17:00:00,26369,3490,29859,484801,514660,-4560,16168,3178976,115557,NaN,NaN,3809193,53885257,24160306.0,216.0,3682451.0,126742.0,42550896.0,11334361.0
416,2021-04-15T17:00:00,25587,3417,29004,481019,510023,-4637,16974,3200196,115937,NaN,NaN,3826156,54204890,24260858.0,211.0,3698718.0,127438.0,42736949.0,11467941.0

In [5]:
list(df_nd.columns)

['data',
 'ricoverati_con_sintomi',
 'terapia_intensiva',
 'totale_ospedalizzati',
 'isolamento_domiciliare',
 'totale_positivi',
 'variazione_totale_positivi',
 'nuovi_positivi',
 'dimessi_guariti',
 'deceduti',
 'casi_da_sospetto_diagnostico',
 'casi_da_screening',
 'totale_casi',
 'tamponi',
 'casi_testati',
 'ingressi_terapia_intensiva',
 'totale_positivi_test_molecolare',
 'totale_positivi_test_antigenico_rapido',
 'tamponi_test_molecolare',
 'tamponi_test_antigenico_rapido']

In [6]:
# Add columns
df_nd['variazione_terapia_intensiva'] = df_nd['terapia_intensiva'].diff()
df_nd['variazione_ricoverati_con_sintomi'] = df_nd['ricoverati_con_sintomi'].diff()
df_nd['variazione_totale_ospedalizzati'] = df_nd['totale_ospedalizzati'].diff()
df_nd['variazione_isolamento_domiciliare'] = df_nd['isolamento_domiciliare'].diff()
df_nd['nuovi_dimessi_guariti'] = df_nd['dimessi_guariti'].diff()
df_nd['nuovi_deceduti'] = df_nd['deceduti'].diff()
df_nd['nuovi_tamponi'] = df_nd['tamponi'].diff()
df_nd['nuovi_casi_testati'] = df_nd['casi_testati'].diff()
df_nd

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
0,2020-02-24T18:00:00,101,26,127,94,221,0,221,1,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2021-04-11T17:00:00,27251,3585,30836,502169,533005,-80,15746,3122555,114254,...,42107589.0,10947277.0,-3.0,-403.0,-406.0,326.0,15486.0,331.0,253100.0,85401.0
413,2021-04-12T17:00:00,27329,3593,30922,493495,524417,-8588,9789,3140565,114612,...,42200462.0,11045039.0,8.0,78.0,86.0,-8674.0,18010.0,358.0,190635.0,50091.0
414,2021-04-13T17:00:00,26952,3526,30478,488742,519220,-5197,13447,3158725,115088,...,42353108.0,11197383.0,-67.0,-377.0,-444.0,-4753.0,18160.0,476.0,304990.0,87678.0
415,2021-04-14T17:00:00,26369,3490,29859,484801,514660,-4560,16168,3178976,115557,...,42550896.0,11334361.0,-36.0,-583.0,-619.0,-3941.0,20251.0,469.0,334766.0,102005.0
416,2021-04-15T17:00:00,25587,3417,29004,481019,510023,-4637,16974,3200196,115937,...,42736949.0,11467941.0,-73.0,-782.0,-855.0,-3782.0,21220.0,380.0,319633.0,100552.0

In [7]:
df_n = df_nd.iloc[1:]
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,tamponi_test_molecolare,tamponi_test_antigenico_rapido,variazione_terapia_intensiva,variazione_ricoverati_con_sintomi,variazione_totale_ospedalizzati,variazione_isolamento_domiciliare,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,NaN,NaN,9.0,13.0,23.0,68.0,0.0,3.0,4299.0,NaN
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,NaN,NaN,1.0,14.0,14.0,59.0,2.0,2.0,964.0,NaN
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,NaN,NaN,20.0,120.0,140.0,63.0,42.0,5.0,2427.0,NaN
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,NaN,NaN,8.0,97.0,105.0,128.0,1.0,4.0,3681.0,NaN
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,NaN,NaN,41.0,56.0,97.0,131.0,4.0,8.0,2966.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2021-04-11T17:00:00,27251,3585,30836,502169,533005,-80,15746,3122555,114254,...,42107589.0,10947277.0,-3.0,-403.0,-406.0,326.0,15486.0,331.0,253100.0,85401.0
413,2021-04-12T17:00:00,27329,3593,30922,493495,524417,-8588,9789,3140565,114612,...,42200462.0,11045039.0,8.0,78.0,86.0,-8674.0,18010.0,358.0,190635.0,50091.0
414,2021-04-13T17:00:00,26952,3526,30478,488742,519220,-5197,13447,3158725,115088,...,42353108.0,11197383.0,-67.0,-377.0,-444.0,-4753.0,18160.0,476.0,304990.0,87678.0
415,2021-04-14T17:00:00,26369,3490,29859,484801,514660,-4560,16168,3178976,115557,...,42550896.0,11334361.0,-36.0,-583.0,-619.0,-3941.0,20251.0,469.0,334766.0,102005.0
416,2021-04-15T17:00:00,25587,3417,29004,481019,510023,-4637,16974,3200196,115937,...,42736949.0,11467941.0,-73.0,-782.0,-855.0,-3782.0,21220.0,380.0,319633.0,100552.0

In [8]:
# Add columns
df_n['ti_su_to'] = ((df_n['terapia_intensiva'] / df_n['totale_ospedalizzati']) * 100).round(2)
df_n['to_su_tp'] = ((df_n['totale_ospedalizzati'] / df_n['totale_positivi']) * 100).round(2)
df_n['np_su_nt'] = ((df_n['nuovi_positivi'] / df_n['nuovi_tamponi']) * 100).round(2)
df_n['np_su_nct'] = ((df_n['nuovi_positivi'] / df_n['nuovi_casi_testati']) * 100).round(2)
df_n['var_ti_perc'] = ((df_n['variazione_terapia_intensiva'] / (df_n['terapia_intensiva'] - df_n['variazione_terapia_intensiva'])) * 100).round(2)
df_n['var_pos_perc'] = ((df_n['variazione_totale_positivi'] / (df_n['totale_positivi'] - df_n['variazione_totale_positivi'])) * 100).round(2)
df_n

,data,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,...,nuovi_dimessi_guariti,nuovi_deceduti,nuovi_tamponi,nuovi_casi_testati,ti_su_to,to_su_tp,np_su_nt,np_su_nct,var_ti_perc,var_pos_perc
1,2020-02-25T18:00:00,114,35,150,162,311,90,93,1,10,...,0.0,3.0,4299.0,NaN,23.33,48.23,2.16,NaN,34.62,40.72
2,2020-02-26T18:00:00,128,36,164,221,385,74,78,3,12,...,2.0,2.0,964.0,NaN,21.95,42.60,8.09,NaN,2.86,23.79
3,2020-02-27T18:00:00,248,56,304,284,588,203,250,45,17,...,42.0,5.0,2427.0,NaN,18.42,51.70,10.30,NaN,55.56,52.73
4,2020-02-28T18:00:00,345,64,409,412,821,233,238,46,21,...,1.0,4.0,3681.0,NaN,15.65,49.82,6.47,NaN,14.29,39.63
5,2020-02-29T18:00:00,401,105,506,543,1049,228,240,50,29,...,4.0,8.0,2966.0,NaN,20.75,48.24,8.09,NaN,64.06,27.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,2021-04-11T17:00:00,27251,3585,30836,502169,533005,-80,15746,3122555,114254,...,15486.0,331.0,253100.0,85401.0,11.63,5.79,6.22,18.44,-0.08,-0.02
413,2021-04-12T17:00:00,27329,3593,30922,493495,524417,-8588,9789,3140565,114612,...,18010.0,358.0,190635.0,50091.0,11.62,5.90,5.13,19.54,0.22,-1.61
414,2021-04-13T17:00:00,26952,3526,30478,488742,519220,-5197,13447,3158725,115088,...,18160.0,476.0,304990.0,87678.0,11.57,5.87,4.41,15.34,-1.86,-0.99
415,2021-04-14T17:00:00,26369,3490,29859,484801,514660,-4560,16168,3178976,115557,...,20251.0,469.0,334766.0,102005.0,11.69,5.80,4.83,15.85,-1.02,-0.88
416,2021-04-15T17:00:00,25587,3417,29004,481019,510023,-4637,16974,3200196,115937,...,21220.0,380.0,319633.0,100552.0,11.78,5.69,5.31,16.88,-2.09,-0.90

In [9]:
df_n.to_csv(csv_out_name, index=False)

In [10]:
df_n[['totale_positivi', 'var_pos_perc', 'variazione_totale_positivi']]
# df_n.columns

     totale_positivi  var_pos_perc  variazione_totale_positivi
1                311         40.72                          90
2                385         23.79                          74
3                588         52.73                         203
4                821         39.63                         233
5               1049         27.77                         228
..               ...           ...                         ...
412           533005         -0.02                         -80
413           524417         -1.61                       -8588
414           519220         -0.99                       -5197
415           514660         -0.88                       -4560
416           510023         -0.90                       -4637

[416 rows x 3 columns]