In [1]:
import sys
import time
import requests
import datetime
import pandas as pd

path_root = '../..'
sys.path.append(f'{path_root}/')
from src.util.functions import Functions as F

# Disable warning
pd.options.mode.chained_assignment = None

level = 'province'

path_data = f'{path_root}/data'
path_csv = f'{path_data}/csv'
csv_out_name = f'{path_csv}/covid19-{level}.csv'

In [2]:
url_cum = F.get_url_cum(level)
url_cum

'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'

In [3]:
df_raw_p = pd.read_csv(url_cum)
list(df_raw_p.columns)

['data',
 'stato',
 'codice_regione',
 'denominazione_regione',
 'codice_provincia',
 'denominazione_provincia',
 'sigla_provincia',
 'lat',
 'long',
 'totale_casi',
 'note',
 'codice_nuts_1',
 'codice_nuts_2',
 'codice_nuts_3']

In [4]:
cols_to_drop = ['stato', 'lat', 'long', 'note']
df_pd = df_raw_p.drop(cols_to_drop, axis=1)
df_pd

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2020-02-24T18:00:00,13,Abruzzo,66,L'Aquila,AQ,0,NaN,NaN,NaN
1,2020-02-24T18:00:00,13,Abruzzo,67,Teramo,TE,0,NaN,NaN,NaN
2,2020-02-24T18:00:00,13,Abruzzo,68,Pescara,PE,0,NaN,NaN,NaN
3,2020-02-24T18:00:00,13,Abruzzo,69,Chieti,CH,0,NaN,NaN,NaN
4,2020-02-24T18:00:00,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
78936,2021-08-23T17:00:00,5,Veneto,27,Venezia,VE,73562,ITH,ITH3,ITH35
78937,2021-08-23T17:00:00,5,Veneto,28,Padova,PD,85464,ITH,ITH3,ITH36
78938,2021-08-23T17:00:00,5,Veneto,29,Rovigo,RO,15147,ITH,ITH3,ITH37
78939,2021-08-23T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,5790,ITH,ITH3,NaN
78940,2021-08-23T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1395,ITH,ITH3,NaN

In [5]:
last_date_str = df_pd.iloc[-1].data.split('T')[0]
last_date = datetime.datetime.strptime(last_date_str, '%Y-%m-%d')
prev_date = F.get_previous_date(last_date)
prev_date_str = datetime.datetime.strftime(prev_date, '%Y-%m-%d')
last_date_str, prev_date_str

('2021-08-23', '2021-08-22')

In [6]:
df_raw_p_1 = df_pd[df_pd.data.str.startswith(last_date_str)]
df_raw_p_1

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
78792,2021-08-23T17:00:00,13,Abruzzo,66,L'Aquila,AQ,19777,ITF,ITF1,ITF11
78793,2021-08-23T17:00:00,13,Abruzzo,67,Teramo,TE,18532,ITF,ITF1,ITF12
78794,2021-08-23T17:00:00,13,Abruzzo,68,Pescara,PE,19124,ITF,ITF1,ITF13
78795,2021-08-23T17:00:00,13,Abruzzo,69,Chieti,CH,20131,ITF,ITF1,ITF14
78796,2021-08-23T17:00:00,13,Abruzzo,879,Fuori Regione / Provincia Autonoma,NaN,637,ITF,ITF1,NaN
...,...,...,...,...,...,...,...,...,...,...
78936,2021-08-23T17:00:00,5,Veneto,27,Venezia,VE,73562,ITH,ITH3,ITH35
78937,2021-08-23T17:00:00,5,Veneto,28,Padova,PD,85464,ITH,ITH3,ITH36
78938,2021-08-23T17:00:00,5,Veneto,29,Rovigo,RO,15147,ITH,ITH3,ITH37
78939,2021-08-23T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,5790,ITH,ITH3,NaN
78940,2021-08-23T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1395,ITH,ITH3,NaN

In [7]:
df_raw_p_0 = df_pd[df_pd.data.str.startswith(prev_date_str)]
df_raw_p_0

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
78643,2021-08-22T17:00:00,13,Abruzzo,66,L'Aquila,AQ,19765,ITF,ITF1,ITF11
78644,2021-08-22T17:00:00,13,Abruzzo,67,Teramo,TE,18528,ITF,ITF1,ITF12
78645,2021-08-22T17:00:00,13,Abruzzo,68,Pescara,PE,19119,ITF,ITF1,ITF13
78646,2021-08-22T17:00:00,13,Abruzzo,69,Chieti,CH,20131,ITF,ITF1,ITF14
78647,2021-08-22T17:00:00,13,Abruzzo,879,Fuori Regione / Provincia Autonoma,NaN,637,ITF,ITF1,NaN
...,...,...,...,...,...,...,...,...,...,...
78787,2021-08-22T17:00:00,5,Veneto,27,Venezia,VE,73496,ITH,ITH3,ITH35
78788,2021-08-22T17:00:00,5,Veneto,28,Padova,PD,85403,ITH,ITH3,ITH36
78789,2021-08-22T17:00:00,5,Veneto,29,Rovigo,RO,15141,ITH,ITH3,ITH37
78790,2021-08-22T17:00:00,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,5788,ITH,ITH3,NaN
78791,2021-08-22T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1388,ITH,ITH3,NaN

In [8]:
# State S
df_raw_p_1 = df_raw_p_1.sort_values(by='codice_provincia').reset_index(drop=True)
df_raw_p_1

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2021-08-23T17:00:00,1,Piemonte,1,Torino,TO,198239,ITC,ITC1,ITC11
1,2021-08-23T17:00:00,1,Piemonte,2,Vercelli,VC,13861,ITC,ITC1,ITC12
2,2021-08-23T17:00:00,1,Piemonte,3,Novara,NO,28915,ITC,ITC1,ITC15
3,2021-08-23T17:00:00,1,Piemonte,4,Cuneo,CN,53299,ITC,ITC1,ITC16
4,2021-08-23T17:00:00,1,Piemonte,5,Asti,AT,17435,ITC,ITC1,ITC17
...,...,...,...,...,...,...,...,...,...,...
144,2021-08-23T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN
145,2021-08-23T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN
146,2021-08-23T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN
147,2021-08-23T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,3,ITC,ITC2,NaN
148,2021-08-23T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1395,ITH,ITH3,NaN

In [9]:
# State S - 1
df_raw_p_0 = df_raw_p_0.sort_values(by='codice_provincia').reset_index(drop=True)
df_raw_p_0

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3
0,2021-08-22T17:00:00,1,Piemonte,1,Torino,TO,198180,ITC,ITC1,ITC11
1,2021-08-22T17:00:00,1,Piemonte,2,Vercelli,VC,13859,ITC,ITC1,ITC12
2,2021-08-22T17:00:00,1,Piemonte,3,Novara,NO,28909,ITC,ITC1,ITC15
3,2021-08-22T17:00:00,1,Piemonte,4,Cuneo,CN,53281,ITC,ITC1,ITC16
4,2021-08-22T17:00:00,1,Piemonte,5,Asti,AT,17422,ITC,ITC1,ITC17
...,...,...,...,...,...,...,...,...,...,...
144,2021-08-22T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN
145,2021-08-22T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN
146,2021-08-22T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN
147,2021-08-22T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,3,ITC,ITC2,NaN
148,2021-08-22T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1388,ITH,ITH3,NaN

In [10]:
df_p = df_raw_p_1.copy()
df_p['variazione_totale_casi'] = df_raw_p_1['totale_casi'] - df_raw_p_0['totale_casi']
df_p

,data,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,totale_casi,codice_nuts_1,codice_nuts_2,codice_nuts_3,variazione_totale_casi
0,2021-08-23T17:00:00,1,Piemonte,1,Torino,TO,198239,ITC,ITC1,ITC11,59
1,2021-08-23T17:00:00,1,Piemonte,2,Vercelli,VC,13861,ITC,ITC1,ITC12,2
2,2021-08-23T17:00:00,1,Piemonte,3,Novara,NO,28915,ITC,ITC1,ITC15,6
3,2021-08-23T17:00:00,1,Piemonte,4,Cuneo,CN,53299,ITC,ITC1,ITC16,18
4,2021-08-23T17:00:00,1,Piemonte,5,Asti,AT,17435,ITC,ITC1,ITC17,13
...,...,...,...,...,...,...,...,...,...,...,...
144,2021-08-23T17:00:00,9,Toscana,995,In fase di definizione/aggiornamento,NaN,0,ITI,ITI1,NaN,0
145,2021-08-23T17:00:00,4,P.A. Trento,996,In fase di definizione/aggiornamento,NaN,0,ITH,ITH2,NaN,0
146,2021-08-23T17:00:00,10,Umbria,997,In fase di definizione/aggiornamento,NaN,0,ITI,ITI2,NaN,0
147,2021-08-23T17:00:00,2,Valle d'Aosta,998,In fase di definizione/aggiornamento,NaN,3,ITC,ITC2,NaN,0
148,2021-08-23T17:00:00,5,Veneto,999,In fase di definizione/aggiornamento,NaN,1395,ITH,ITH3,NaN,7

In [11]:
# Write df to csv
df_p.to_csv(csv_out_name, index=False)